stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    #cmd: ../Mlops-task/src/load_data.py --config=params.yaml
    deps:
      #- src/get_data.py
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\src\get_data.py
      #- src/load_data.py
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\src\load_data.py
      #- data_given/Admission_Prediction.csv
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data_given\Admission_Prediction.csv
    outs:
      #- data/raw/Admission_Prediction.csv
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\raw\Admission_Prediction.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      #- src/split_data.py
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\src\split_data.py
      #- data/raw/Admission_Prediction.csv
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\raw\Admission_Prediction.csv
    outs:
      #- data/processed/train_Admission_Prediction.csv
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\processed\train_Admission_Prediction.csv
      #- data/processed/test_Admission_Prediction.csv
      - C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\processed\test_Admission_Prediction.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_Admission_Prediction.csv
      - data/processed/test_Admission_Prediction.csv
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
    outs:
      - saved_models/model.joblib

## dvc repro
## dvc metrics diff
## dvc metrics show