base:
  project: Admission_prediction-project
  random_state: 1
  target_col: Chance_of_Admit

data_source:
  #s3_source: data_given/Admission_Prediction.csv
  s3_source: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data_given\Admission_Prediction.csv

load_data:
  #raw_dataset_csv: data/raw/Admission_Prediction.csv
  raw_dataset_csv: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\raw\Admission_Prediction.csv

split_data:
  #train_path: data/processed/train_Admission_Prediction.csv
  train_path: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\processed\train_Admission_Prediction.csv
  #test_path: data/processed/test_Admission_Prediction.csv
  test_path: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\data\processed\test_Admission_Prediction.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
       alpha: 0.88
       l1_ratio: 0.89
      #alpha: 0.9
      #l1_ratio: 0.4
model_dir: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\saved_models

reports:
  #params: report/params.json
  params: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\report\params.json
  #scores: report/scores.json
  scores: C:\Users\VIMALA P T\OneDrive\Documents\Python anaconda\Ineuron\projects\MLOPS\Mlops-task\report\scores.json

webapp_model_dir: prediction_service/model/model.joblib